version: '3.7'
services:
  crm:
    build:
      context: CRMGo
      dockerfile: ./cmd/crm/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=0.tcp.eu.ngrok.io
      - DB_PORT=10717
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=root
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - GIT_NAME=HAndHTemp
      - GIT_TOKEN=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
  crm_backend:
    build:
      context: CRMC#
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./logs:/app/logs
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crm
      - crm_backend
      - frontend