version: '3.7'
services:
  postgres:
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./CRMGo/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./CRMGo/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
  crm:
    build:
      context: CRMGo
      dockerfile: ./cmd/crm/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=root
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - GIT_NAME=HAndHTemp
      - GIT_TOKEN=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
    depends_on:
      postgres:
        condition: service_healthy
  crm_backend:
    build:
      context: CRMC#
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./logs:/app/logs
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - crm
      - crm_backend
      - frontend